### ISSUE TITLE
Suggestion to update README file

### ISSUE THREAD

**Issue by Laurendelgiudice** [FhenixProtocol/fhenix-hardhat-example#3]
Consider adding the missing steps as below when starting from scratch before running **pnpm localfhenix:start**:

- create .env file containing KEY value (dotenv compatibility for hardhat)
- Launch docker service manually if needed (error during connect: This error may indicate that the docker daemon is not running). In my case I launched docker-desktop.

**Comment by Cashmaney** [comment]
Done. Better late than never 😄
